### ISSUE TITLE
addprocs_sge works incorrectly if the work directory is not the home directory and the list of default options for qsub includes "-cwd"

### ISSUE THREAD

**Issue by rsarfati** [JuliaParallel/ClusterManagers.jl#103]
In our environment, the list of default options for qsub includes "-cwd" to preserve the current directory. If the current working directory is different from the user's home directory, addprocs_sge doesn't work (can't find the files with the information about workers). From the file, qsub.jl:
```julia
filenames(i) = "$home/julia-$(getpid()).o$id-$i","$home/julia-$(getpid())-$i.o$id","$home/julia-$(getpid()).o$id.$i"
```

Julia expects these files in the home dir, but they are created in the current dir instead.

**Comment by vchuravy** [comment]
Thanks for reporting! Would you be able to open a PR to fix this? I don't have access to a QSub environment so testing the code is hard for me :)

**Comment by bjarthur** [comment]
closed by https://github.com/JuliaParallel/ClusterManagers.jl/pull/153
