### ISSUE TITLE
warn function call in slurm.jl needs to be changed to a macro to be compaticle with v1

### ISSUE THREAD

**Issue by jishnub** [JuliaParallel/ClusterManagers.jl#115]
https://github.com/JuliaParallel/ClusterManagers.jl/blob/805baa2a57bdccaf69ce086c1d26d3ad286bb68a/src/slurm.jl#L52

The warn needs to be changed to a macro to be compatible with v1

**Comment by vchuravy** [comment]
You are welcome to submit a PR!

**Comment by miguelraz** [comment]
Bump closing by #119
