### ISSUE TITLE
Make ElasticManager print out connection instructions

### ISSUE THREAD

**Issue by marius311** [JuliaParallel/ClusterManagers.jl#128]
Hi guys, I'm wondering if you'd accept a PR (which I can do) that would for convenience make creating an ElasticManager print out a string giving you a command you can just copy/paste to launch workers? I already have this in https://github.com/marius311/NerscClusterManagers.jl/ but its pretty generic and not actually tied to the specific cluster mentioned there, and I could incorporate it here. Just wanted to ask first before taking the time to do it. 

The way it would look roughly is e.g.:

```julia

julia> ElasticManager()

To connect workers:
/home/marius/src/julia-1.3/usr/bin/julia --project=/home/marius/myproject/Project.toml -e 'using ClusterManagers; ClusterManagers.elastic_worker("YpKuAGX41CEAOhsz","10.0.0.24",44136)'

ElasticManager:
  Active workers : []
  Number of workers to be added  : 0
  Terminated workers : []

```

Note the full path to the executable and current environment are included so you get a worker in the exact same state. The port is chosen ephemerally if not specified and the IP address is detected using `hostname` (in this possible PR, I'd probably add some failsafes for if these thing dont work on a given system, eg on Windows)

**Comment by tanmaykm** [comment]
Yes, that seems useful. I wonder if it should be a separate method though, rather than the `show` method.

**Comment by marius311** [comment]
> I wonder if it should be a separate method though, rather than the show method.

**Comment by marius311** [comment]
Anyway, will work on a PR.

**Comment by tanmaykm** [comment]
> I would say it does make sense in the show method, ...

Having it as a separate method would for example make it easier to use the output directly as a command. While `show` is nice on a REPL, it's not amenable for programmatic use IMO.
