### ISSUE TITLE
Can't add additional nodes

### ISSUE THREAD

**Issue by grahamas** [JuliaParallel/ClusterManagers.jl#129]
```
julia> addprocs(SlurmManager(2))
julia> addprocs(SlurmManager(2))
```
I would naively expect the above to result in a total of 4 nodes.  Alternatively, I might with a little more thought expect that I should have saved the SlurmManager and somehow added nodes to that. I'm happy to try to fix this either way, but could someone tell me the expected behavior?

**Comment by juliohm** [comment]
In general the idea is to have a single `addprocs` call at the beginning of your script. Any more advanced usage needs to be documented, and I don't think we are at this stage of documentation yet. Closing the issue for now. We will try to be more active in this repository moving forward.
