### ISSUE TITLE
NodeFile and qsub script

### ISSUE THREAD

**Issue by tlamadon** [JuliaParallel/ClusterManagers.jl#13]
I have been adapting some code from the google group for Julia to parse the node file given from a `qsub` command. 

The difference with the existing `qsub` launcher is that `qsub` should not be called, only the the node file. The goal is to be able to start parallel jobs without requiring the interactive session.

The idea is to call `qsub` from the command line, then the `qsub` script calls Julia, which then parses the node file in the environment and adds the workers at the beginning.

I have a working version of my code, but not wrapped into a ClusterManager:
https://gist.github.com/tlamadon/636d8e468b328d23bb4d

In the code I use addprocs to connect the workers. The problem I have is that I don't know how to wrap this into a ClusterManager. It seems to me that addprocs actually uses the local manager already. 

Any suggestion would be very welcome, I will be happy to write the ClusterManager and send a merge request,

**Comment by juliohm** [comment]
Too old to reproduce. Closing.
