### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by juliohm** [JuliaParallel/ClusterManagers.jl#143]
Can you please trigger a new release of this package?

**Comment by vchuravy** [comment]
Would you be willing to help with maintenance? I can add you as a maintainer.

**Comment by vchuravy** [comment]
https://github.com/JuliaParallel/ClusterManagers.jl/issues/118#issuecomment-612666211

**Comment by juliohm** [comment]
I'd be happy to maintain to the best extent possible. I don't think avoiding releases is a good strategy here.

Currently I can test and debug the LSF manager because that is what the company uses. But we never know where we will go next and if we will still have access to the manager.
