### ISSUE TITLE
Possibly naive question: ClusterManagers work for kubernetes?

### ISSUE THREAD

**Issue by nickeubank** [JuliaParallel/ClusterManagers.jl#146]
Trying to get Julia up on an AzureML cluster, or if not that than a plain kubernetes cluster on Azure, but can't find much on how to do it in Julia. Don't *see* anything here, but maybe I'm just missing it -- can ClusterManagers be useful for scaling clusters?

**Comment by bjarthur** [comment]
https://juliacomputing.com/products/juliarun

**Comment by nickeubank** [comment]
@bjarthur No objection to Julia Computing making money providing support, but looking for an open source solution.

I take it that isn't in `ClusterManagers` then?

**Comment by juliohm** [comment]
Thank you @nickeubank for opening the issue. I think you can find more resources in https://github.com/JuliaComputing/Kuber.jl ClusterManagers.jl is currently under review, but I assume that the workflow model we are seeking in this package here is biased towards classical MPI jobs.

I will close the issue given that you can find better answers elsewhere in the community forums.
