### ISSUE TITLE
Extra options on SGE

### ISSUE THREAD

**Issue by nantonel** [JuliaParallel/ClusterManagers.jl#151]
In our cluster in order to run a job on SGE we need to specify an additional option which indicates our group.

I manage to add this by modifying [qsub.jl](https://github.com/JuliaParallel/ClusterManagers.jl/blob/master/src/qsub.jl) adding the kwarg `opt`:
```julia
addprocs_sge(np::Integer; queue::AbstractString="", qsub_env::AbstractString="", res_list::AbstractString="", opt::Cmd=``) =
        addprocs(SGEManager(np, queue),qsub_env=qsub_env,res_list=res_list,opt=opt)
```
which should be a `Cmd` and can interpolate correctly in `qsub_cmd`:
```julia
`qsub -N $jobname -terse -j y -R y -t 1-$np -V $res_list $queue $qsub_env $opt`
```
Do you think it makes sense? In case I could prepare a PR. Thanks!

**Comment by bjarthur** [comment]
why not just use `qsub_env`?

**Comment by nantonel** [comment]
We could use that argument, but it still need more modifications:
```julia
        if params[:qsub_env] == ""
            qsub_env = ``
        else
            evar = params[:qsub_env]
            qsub_env = `-v $evar`
        end
```
since the option I need doesn't belong to the `-v` option.

**Comment by bjarthur** [comment]
oh, right.  and `queue` and `res_list` also are suffixed to hard-coded flags.  maybe it would be simpler to replace all of them with a single `options` argument that is appended to the `bsub` and have the user specify the fixed flags explicitly?

**Comment by nantonel** [comment]
yes I think that solution would be much cleaner!

**Comment by bjarthur** [comment]
closed by https://github.com/JuliaParallel/ClusterManagers.jl/pull/153
