### ISSUE TITLE
Document usage

### ISSUE THREAD

**Issue by GlenHertz** [JuliaParallel/ClusterManagers.jl#16]
Hi,

I'm interested in using this with SGE but I'm not sure how to use it.  The documentation covers how to write a new manager but has no examples about how to use the existing ones.  It seems like this is for starting new Julia workers and not for lunching Cmds.  That is fine but it would be nice to have some examples of the typical usage.

Glen

**Comment by diegopenhanut** [comment]
Thank you @jakebolewski ! I really missed an example like this.

**Comment by ViralBShah** [comment]
Could this be contributed back into the README?
