### ISSUE TITLE
ClusterManagers can be run on top of dask clusters!

### ISSUE THREAD

**Issue by hhuuggoo** [JuliaParallel/ClusterManagers.jl#186]
Hi - this isn't really an issue, but I just wanted to report that ElasticManagers can be run on top of dask clusters! We've been experimenting with this at [Saturn Cloud](https://saturncloud.io/). The following writeup is still very preliminary, and also quite brittle.

On your workstation, install ClusterManagers 

```
julia -e 'using Pkg; Pkg.add(url="https://github.com/JuliaParallel/ClusterManagers.jl")'
```
Start the ElasticManager on the julia instance:

```
julia> using ClusterManagers;

julia> em = ElasticManager(addr=:auto, port=8999, printing_kwargs=(absolute_exename=false, same_project=false))
ElasticManager:
  Active workers : []
  Number of workers to be added  : 0
  Terminated workers : []
  Worker connect command :
    julia -e 'using ClusterManagers; ClusterManagers.elastic_worker("gYJIVmvRlvyKirF7","192.168.235.67",8999)'
```

2. Tell the dask cluster to install ClusterManagers on all workers:

```
from dask_saturn import SaturnCluster # of course you can replace this with your dask cluster of choice.
sc = SaturnCluster()
from distributed import Client
c = Client(sc)
install_cmd = """julia -e 'using Pkg; Pkg.add(url="https://github.com/JuliaParallel/ClusterManagers.jl")'"""
cmd = """julia -e 'using ClusterManagers; ClusterManagers.elastic_worker("gYJIVmvRlvyKirF7","192.168.235.67",8999)'"""

def run(cmd):
    import subprocess
    return subprocess.check_output(cmd, shell=True, stderr=subprocess.STDOUT)

workers = c.scheduler_info()["workers"]
worker_names = list(workers.keys())
futs = []
for w in worker_names:
    futs.append(
        c.submit(run, install_cmd, pure=False)
    )
c.gather(futs)
```

3. Tell the dask cluster to spin up julia workers:

```
futs = []
for w in worker_names:
    futs.append(
        c.submit(run, cmd, pure=False)
    )
c.gather(futs)
```

5. Check the cluster in julia:

```
julia> em
ElasticManager:
  Active workers : [ 2,3,4]  <----- WE HAVE 3 ACTIVE WORKERS!!
  Number of workers to be added  : 0
  Terminated workers : []
  Worker connect command :
    julia -e 'using ClusterManagers; ClusterManagers.elastic_worker("gYJIVmvRlvyKirF7","192.168.235.67",8999)'
```

The dask code above is pretty brittle - To do it properly, we would want to make sure that we don't get zombie processes as workers are restarted, etc. But those are all easily solvable problems.

**Comment by Moelf** [comment]
this is probably the wrong way of doing this, `dask` uses some underlying HPC cluster system right? shouldn't Julia be able to directly utilize that?

**Comment by hhuuggoo** [comment]
Not for us - our product manages dask clusters, we don't expose the underlying k8s layer to users for security reasons, For our users bootstrapping other cluster types on top of cluster types we already support is useful. So for us this is definitely the right approach even if it's a bit odd.
