### ISSUE TITLE
Slurm error

### ISSUE THREAD

**Issue by pearcemc** [JuliaParallel/ClusterManagers.jl#23]
Hello

I'm just getting started with HPC, my submission system is slurm. 
I'm getting this error when trying to start up some processes:

```julia
julia> using ClusterManagers
julia> addprocs(SlurmManager(2), partition="debug", t="00:5:00")
Error launching Slurm job:
MethodError(length,(:all_to_all,))
0-element Array{Int64,1}
```
Is it necessary to write a submission script and submit before this works? If so, what should one look like?

Any suggestions appreciated!

**Comment by andreasnoack** [comment]
Please try `Pkg.checkout("SlurmManager")` to get the latest version. I believe this issue has been fixed.

**Comment by pearcemc** [comment]
Thanks, I'll give it a go next chance I get.

**Comment by pearcemc** [comment]
Thanks again. This particular problem solved by ensuring the ClusterManagers git repo on my machine matched the master branch here.
