### ISSUE TITLE
Trivial example with Slurm is failing

### ISSUE THREAD

**Issue by eschnett** [JuliaParallel/ClusterManagers.jl#31]
The commands
```
using ClusterManagers
addprocs(SlurmManager(2))
```
fail with
```
Error launching Slurm job:
MethodError(length,(:all_to_all,))
0-element Array{Int64,1}
```
It seems that the `launch` function receives a keyword argument `:topology=>:all_to_all` that isn't handled well.

**Comment by gabrielgggg** [comment]
Same here:

    julia> using ClusterManagers
    julia> addprocs(SlurmManager(2), partition="debug", t="00:5:00")
    Error launching Slurm job:
    MethodError(length,(:all_to_all,))
    0-element Array{Int64,1}

This is on

    slurm 14.11.9

**Comment by andreasnoack** [comment]
Have you tried to check out master?

**Comment by gabrielgggg** [comment]
@andreasnoack No, this was straight from `Pkg.add()`. I'm not 100% sure how package versioning works in Julia.

**Comment by gcamilo** [comment]
Try ```Pkg.checkout("ClusterManagers")```

**Comment by eschnett** [comment]
Yes, the master is working. I think we should create a new version from the master for Julia 0.4.

**Comment by gcamilo** [comment]
If this does happen, my pull request should be merged, as otherwise qsub is broken if you want to name a queue. I didn't realize this in my previous one.

**Comment by gabrielgggg** [comment]
> Try `Pkg.checkout("ClusterManagers")`

This fixes the issue, for the record. Thank you!

**Comment by jiahao** [comment]
Cross-ref: https://groups.google.com/forum/#!topic/julia-users/HtfXgp8sCgc
