### ISSUE TITLE
Proper ClusterManager config for SharedArrays in SGE environment

### ISSUE THREAD

**Issue by klkeys** [JuliaParallel/ClusterManagers.jl#34]
I am trying to run a Julia script in an SGE environment on my department's compute cluster. The script makes heavy use of `SharedArray` objects, so I need to tell both Julia and the SGE scheduler to allocate workers on the same node.

I tried it with the SGE [ORTE](https://docs.oracle.com/cd/E19923-01/820-6793-10/Introduction.html#50524188_62507), which is probably better for `DArray` environments. I asked my sysadmin to add a new parallel environment for OpenMP with [this website](http://star.mit.edu/cluster/mlarchives/0707.html) as a guide.

In the meantime, I want to ensure that my Julia code is at least attempting to correctly allocate the workers locally. I schedule my Julia script with `qsub -pe orte 11 script.jl` and then add the following code to the top of my script:

```
# set up cluster manager
using ClusterManagers
addprocs(LocalAffinityManager(np = 10, mode = COMPACT, affinities = Int[]))

# check if all cores on same host (node)
hosts = []
pids = []
for i in workers()
    host, pid = fetch(@spawnat i (gethostname(), getpid()))
    push!(hosts, host)
    push!(pids, pid)
end
println("driver process is hosted on ", gethostname())
println("number of workers on host is ", nworkers())
println("where are workers hosted?")
display(hosts)
```

The last SGE run scheduled 6 processes on one node and 5 on the other. I expected that the previous code would show the workers allocated to two hosts. Instead, all worker processes claimed to reside on the same node:

```
driver process is hosted on compute-0-8.local
number of workers on host is 10
where are workers hosted?
10-element Array{Any,1}:
 "compute-0-8.local"
 "compute-0-8.local"
 "compute-0-8.local"
 "compute-0-8.local"
 "compute-0-8.local"
 "compute-0-8.local"
 "compute-0-8.local"
 "compute-0-8.local"
 "compute-0-8.local"
 "compute-0-8.local"
```

How should I configure my `ClusterManager` to place all processes on the same node? (and how do I tell SGE to do the same?!)

**Comment by pearcemc** [comment]
Hi. I ran into a similar issue and made some code in a separate package: https://github.com/pearcemc/ClusterUtils.jl .  The function `describepids` and returns a dict with keys corresponding to the lowest numbered process on each node and values being lists of the processes on those nodes. I also have some code somewhere for ensuring the resulting arrays are named eveywhere they need to be.

**Comment by klkeys** [comment]
@pearcemc I couldn't get the ClusterUtils code to work, so I filed an issue on the repo.

But while I have your attention, is the premise behind `describepids` that I can use the process IDs that it returns for initializing the `SharedArray`s?

**Comment by pearcemc** [comment]
Thanks for filing the issue there. Yeah, that's the idea it provides the id of a representative process on each machine as a key to a list of the procs on the machine - which can be passed as the pids argument of a `SharedArray'. So you can create an appropriate array on each machine by iterating over the keys.

**Comment by juliohm** [comment]
Too old to reproduce. Please consider the latest release of the project.
