### ISSUE TITLE
SGEManager creates many temporary files in working directory

### ISSUE THREAD

**Issue by andreasnoack** [JuliaParallel/ClusterManagers.jl#38]
@amitmurthy Is this necessary for the manager to work or could they be created in the temp folder?

**Comment by amitmurthy** [comment]
I am not familiar with SGE, but a reading of http://gridscheduler.sourceforge.net/htmlman/htmlman1/qsub.html lists `-e` and `-o` options for specifying STDOUT/STDERR redirection filenames.

Should be a simple change to support it.

**Comment by bjarthur** [comment]
if your cluster has `qrsh` in addition to `qsub` you might try the `QRSHManager` instead.

this is actually my preferred manager as our shared filesystem has a cache that is tuned for high throughput at the expense of latency.  inter-process communication via a file is hence highly unreliable.

**Comment by bjarthur** [comment]
see https://github.com/JuliaParallel/ClusterManagers.jl/pull/8#issuecomment-38463229

in short, these temporary files are how the workers communicate their TCP/IP host:port info back to the master process.
