### ISSUE TITLE
Change scheduler manager

### ISSUE THREAD

**Issue by rveltz** [JuliaParallel/ClusterManagers.jl#41]
Hi,

This is not really an issue but more like a question. 

 Do you know if it is possible to use OAR instead of SLURM. Indeed, the cluster I want to use is set for OAR as manager. 

Thank you for your help, 

Best regards.

**Comment by rveltz** [comment]
Sorry what I mean is that OAR is the scheduler... Can we set Julia for OAR?

**Comment by jakebolewski** [comment]
@rveltz you would have to write your own `ClusterManager` type for OAR and implement the required methods.  See the various `ClusterManagers` that implement the interface in this package.

**Comment by rveltz** [comment]
Thank you for your help.
