### ISSUE TITLE
Adding processes to HTCondor 

### ISSUE THREAD

**Issue by PGimenez** [JuliaParallel/ClusterManagers.jl#51]
When adding a process to an HTCondor cluster I get the following output:
julia> using ClusterManagers
julia> addprocs_htc(1)
Submitting job(s).
Waiting for 1 workers: 

Then nothing happens, the function is stuck. I'm on Julia 0.5 and also have tried on 0.4 with the same result. I am able to manually submit jobs to the cluster from the terminal.

Edit: I'm running the cluster on localhost and all the server ports are closed except for the ssh port which might be why the jobs aren't submitted correctly.

**Comment by grero** [comment]
Hi,
 Did you try looking at the error produced by the worker? I faced a similar problem, and looking at the output files in ~/.julia-htc/julia-<jobnr>-1.e I discovered that the environment was not exported, which gave an error like this: 

```julia
fatal: error thrown and no exception handler available.
Base.InitError(mod=:Pkg, error=Base.KeyError(key="HOME"))
```
I'm still working on how to resolve that issue, though.

**Comment by EdgarMCR** [comment]
Hi, 
I get the same error as grero but I am just using vanilla julia and condor and run the julia file from a bash script. At the start of the bash script I run 
`eval  julia --version`
which nicely outputs 
`julia version 0.5.0`
and then produces the same error as grero.

**Comment by azraq27** [comment]
I just submitted a patch that fixes it on my machine. All it does it add the HOME environment variable to the Condor worker submission

**Comment by grero** [comment]
Just applied the patch from @azraq27 on my local clone of the repo. It seemed to help (I also had to add the PATH environment variable), in that the worker doesn't die immediately, but now it just seems to wait indefinitely to connect to the master process. This could be a network issue, but I'm not at all sure how to debug it, since no output is produced.

**Comment by azraq27** [comment]
It writes the STDOUT and STDERR into *.o and *.e files in the `~/.julia-htc` directory. Does the STDERR give you some idea of why the process isn't starting?

**Comment by grero** [comment]
Thanks, it turns out that there was a problem with my network setup, unrelated to ClusterManagers. The patch completely solved the problem on the julia end for me.

**Comment by ivborissov** [comment]
Hi, does condor.jl support running HTCondor on Windows environment?

**Comment by juliohm** [comment]
Too old to reproduce.
