### ISSUE TITLE
Support for different PBS versions

### ISSUE THREAD

**Issue by marius311** [JuliaParallel/ClusterManagers.jl#55]
TBH I don't know much about PBS at all, but thought I'd put this info here in case its useful to someone or maybe prompts some changes to this repo. 

Basically, I'm on a cluster with,

```
$ qsub --version
pbs_version = PBSPro_10.0.9.110976
```

For this version, it seems the flag for an array job is `-J` rather than `-t`, so initially I was getting a `invalid option -- t` error. Additionally, once I fixed that, it was also saying `cannot submit non-rerunable Array Job`, so I had to add `-r y`. Thus my final qsub command [here](https://github.com/JuliaParallel/ClusterManagers.jl/blob/3007d0190885fefaf5702056a514e3625ab46bb1/src/qsub.jl#L72) looks like:

```
`qsub -N $jobname -j oe -r y -k o -J 1-$np $queue $qsub_env $res_list`
```

Also, the output files created have a `.` instead of a `-` separating the job number [here](https://github.com/JuliaParallel/ClusterManagers.jl/blob/3007d0190885fefaf5702056a514e3625ab46bb1/src/qsub.jl#L84), so I had to change that to

```
"$home/julia-$(getpid()).o$id.$i"
```

With those changes, it now works beautifully on my setup. I have no idea how non-standard these things are, but I suppose it would be nice to be able to specify them from the `addprocs` call so I don't have to hack the code myself, and perhaps even nicer if this could somehow be auto-detected.

**Comment by juliohm** [comment]
We have released a new version of the package. Please check there if the issue is till valid.

**Comment by StuartBenjamin** [comment]
This issue is still open, the new package's version of addprocs_pbs doesn't work with PBSpro
