### ISSUE TITLE
Add transport to ElasticManager

### ISSUE THREAD

**Issue by mikewl** [JuliaParallel/ClusterManagers.jl#64]
I'm still busy setting things up to get the elastic manager running on my local network and in a docker image running in ecs but I wondered if a transport option which connected the workers via an ssh tunnel would work? SSH works fine so it should theoretically be an adaptation of the elastic manager with aspects of the ssh manager included.

I'm unsure as to whether this has any merit. If this seems like a good idea then I should be able to make an attempt next week at it. 
Using the elastic manager solves my problem where I would have PCs going off an on so with some extra effort to get it running and retrying once I can get connections to work over the network, the elastic manager becomes a great solution!

**Comment by fredcallaway** [comment]
Bump. I need this, but I have no idea how I would start trying to implement it (no experience with network programming).

**Comment by juliohm** [comment]
We have released a new version of the package. Please double check if the issue is still valid. Also, please provide a MWE.
