### ISSUE TITLE
`addprocs_sge` does not allow user to set queue switch

### ISSUE THREAD

**Issue by GlenHertz** [JuliaParallel/ClusterManagers.jl#68]
Hi,

To launch with qsub I need to be able to set the queue with the `-P` switch (`qsub -P queue_name`).  However the code uses `qsub -q queue_name` but that will not work for me.  I'm willing to submit a PR but I'm not sure how it should be added.  Perhaps with a keyword argument:  `addprocs_sge(5, queue="fast", queue_switch="-P")` or if the queue name starts with a `-` and there is a space then assume it includes the switch?  What do people prefer?

Glen

**Comment by juliohm** [comment]
@GlenHertz please open a PR against the latest master branch. We are trying to revive this package after some time without maintainers.
