### ISSUE TITLE
Example of reading cookie from (shared) file?

### ISSUE THREAD

**Issue by sbromberger** [JuliaParallel/ClusterManagers.jl#69]
Hi all,

I'm sorry to do this, but I've been looking through the code most of the afternoon and I'm still lost as to how to manage this issue. Basically, I'm not allowed to have the cluster cookie passed via command line since it's visible to all users of the system. It *is* allowed to have the workers read a file (owned by me in a shared file) for the cookie.

I've read the docs where it says
> Note that environments requiring higher levels of security can implement this via a custom ClusterManager. For example, cookies can be pre-shared and hence not specified as a startup argument.

but I can't figure out how to do this.

Ideally, I'd modify the Slurm connection manager to allow cookies to be read from a particular location, but again - I don't even know where to start. Any advice appreciated.

**Comment by tanmaykm** [comment]
Maybe we need to have a way to specify the `-i` flag for `srun` to redirect stdin (https://slurm.schedmd.com/srun.html) to read from a shared cookie file?

**Comment by juliohm** [comment]
I will close this issue for now given that it is more like a question. We are trying to revive this package, and so we need to cleanup the issue tracker and the outdated PRs. A new release is out.
