### ISSUE TITLE
SLURM: `srun` doesn't see julia instance using ClusterManagers?

### ISSUE THREAD

**Issue by nickeubank** [JuliaParallel/ClusterManagers.jl#84]
I started a session with an `sbatch` script with:

```
#!/bin/bash
#SBATCH --ntasks=4
#SBATCH --ntasks-per-node=2
#SBATCH --mem-per-cpu=1G
#SBATCH --job-name=my_first_parallel_julia
#SBATCH --time=00-00:02:00  # Wall Clock time (dd-hh:mm:ss) [max of 14 days]
#SBATCH --output=julia_in_parallel.output  # output and error messages go to this file

julia  my_first_parallel_julia_on_slurm.jl
```

Then in my julia script, tried to run `addprocs_slurm(3)` but got this error:

```
srun: Warning: can't honor --ntasks-per-node set to 2 which 
doesn't match the requested tasks 3 with the number of requested nodes 2.
```

But if I run `addprocs_slurm(4)`, it works fine, even thought it _seems_ like that means I have 5 processes working (the master + 4 workers)... 

What am I missing?

**Comment by vchuravy** [comment]
I think this is how it is supposed to be working.  ClusterManager uses `srun` to start processes on the cluster within the `sbatch` allocation. But the first process does not count as such since it is not itself run under `srun`. 


> When the job allocation is finally granted for the batch script, Slurm runs a single copy of the batch script on the first node in the set of allocated nodes.
https://slurm.schedmd.com/sbatch.html

So you would need to say: 
```
#!/bin/bash
#SBATCH --ntasks=4
#SBATCH --ntasks-per-node=2
#SBATCH --mem-per-cpu=1G
#SBATCH --job-name=my_first_parallel_julia
#SBATCH --time=00-00:02:00  # Wall Clock time (dd-hh:mm:ss) [max of 14 days]
#SBATCH --output=julia_in_parallel.output  # output and error messages go to this file

srun --ntasks=1 julia  my_first_parallel_julia_on_slurm.jl
```

Will run `julia` under slurm and then use `srun` to start additional workers, but I am not a 100% sure that this will work as expected since I don't have a slurm cluster handy.

**Comment by nickeubank** [comment]
Thanks @vchuravy . 

That does seem a little odd to me -- it's letting that first julia process run, and I can't think of a reason SLURM allow a process to run if it weren't part of that resource allocation. Seems inherently problematic to allow users to just sneak in processes like that. 

(Also, [the example slurm scripts](http://www.accre.vanderbilt.edu/?page_id=2154#torque) I've seen don't use that `srun` notation...)

**Comment by vchuravy** [comment]
Yeah it is an odd quirk of SLURM. The example scripts from NERSC all use
`srun`
http://www.nersc.gov/users/computational-systems/cori/running-jobs/example-batch-scripts/

My take is to talk to your admins. If they are okay with running a
lightweight master process outside srun. But generally I would use srun for
the master process as well.

**Comment by nickeubank** [comment]
Ah, interesting. OK, bringing up with IT staff. Will get back to you with resolution.

**Comment by nickeubank** [comment]
@vchuravy Checked with IT staff, and they say:

> Everything executed within the
> script is ran within the allocated resources. Only parallel processes (i.e.
> MPI) must be launched with srun. Any application launched without srun will
> just execute one copy of itself on the first node of the job allocation where
> the batch script runs.
> 
> As for the issue you reported in the GitHub repository, after consulting with
> the Slurm developers, we agree that that is not a Slurm issue, but how
> ClusterManagers interacts with Slurm. Namely, if it wants to spawn only a
> subset of the tasks allocated for the job, it should clear the value of the
> SLURM_NTASKS_PER_NODE environment variables before spawning tasks via srun.
> Hence it is a Julia bug.

**Comment by vchuravy** [comment]
Thanks for getting back to me with that. The reasoning seems wird to me since Julia is starting `parallel processes` and is relying on `srun` to setup those instances...
I don't quite see how clearing `SLURM_NTASKS_PER_NODE` would be helping.

**Comment by nickeubank** [comment]
Not sure either -- is the exception being thrown by `julia` or Slurm? If the later, then maybe ClusterManagers.jl should store the value and clear it, then allocate according to that value one process at a time in a manner consistent with the initial request, but in a way that doesn't annoy slurm?

Sorry, not quite sure how this works internally....

**Comment by vchuravy** [comment]
The warning is coming from SLURM and not from Julia. I am confused by the fact that `addprocs_slurm(4)` works since that means it can fullfill the request properly and is ignoring the master process in accounting.

**Comment by nickeubank** [comment]
Perhaps the last `srun` is effectively asking for a new allocation that's small enough it happens to be getting it quickly? I was playing with this over the holidays when I assume system demand was low...

**Comment by vancleve** [comment]
This is helpful I think: https://stackoverflow.com/a/43799481/1596965

**Comment by juliohm** [comment]
Please consult https://github.com/juliohm/julia-distributed-computing for an example on how you should parallelise your program with batch scripts.
