### ISSUE TITLE
Jobfile is incorrect on some PBS clusters

### ISSUE THREAD

**Issue by akels** [JuliaParallel/ClusterManagers.jl#85]
When I submit an array job to the cluster with a command:
```
qsub -N test -j oe -k o -t 1:5 ./test
```
I get list of log files in a form
```
test-1.o50084
test-2.o50084
test-3.o50084
test-4.o50084
test-5.o50084
```
which is different from logfile form ClusterManagers is now looking namely - <job name>.o<id>-<i>. In cluster I have access `qsub --version` is 4.2.10. Seems until 6.0.0 output schematics had changed as can be seen in [this](https://github.com/JuliaParallel/ClusterManagers.jl/pull/47) issue. But seems this specific detail is undocumented. 

When changing schematics manually in qsub.jl cluster worked fine. Thus this might be an annoying bug for newcomers with an easy fix. For example filename(i) could return a list of files which would be checked in the loop or there could be another condition which decide the schematics of filenames depending on `qsub` version.

**Comment by vchuravy** [comment]
If you feel up for it we would welcome a pull request with changes to that effect.
