### ISSUE TITLE
Print does not work without workaround

### ISSUE THREAD

**Issue by akels** [JuliaParallel/ClusterManagers.jl#87]
I don't know if that was intended but `println` and other output commands does not work where run(`echo "Hello"`) works well. Thus I have been overloading `println` after I start cluster:
```
@everywhere import Base.println
@everywhere println(x::AbstractString) = run(`echo "$x"`)
```  
But I wonder if this workaround could find a place in the package?

**Comment by juliohm** [comment]
This issue is not related to the package, but to Distributed computing in general. Closing.
