### ISSUE TITLE
PBSPro qsub does not have -t

### ISSUE THREAD

**Issue by hearnsj** [JuliaParallel/ClusterManagers.jl#89]
Hello. I tried to use the ClusterManagers package on our cluster which uses PBSPro version 13 (I also hae version 14 available). The result is below.
I think the -t option is specific to OpenPBS with Torque (I may be wrong!)
I am happy to help with a port to PBSPro

Also note that on our cluster you cannot submit directly to a queue.
Jobs go to the entry queue and are the sent to queues depending on the resources which you request, including walltime. So the empty queue must work.

John Hearns

julia> addprocs_pbs(12,queue="long")
qsub: invalid option -- 't'
usage: qsub [-a date_time] [-A account_string] [-c interval]
        [-C directive_prefix] [-e path] [-f ] [-h ] [-I [-X]] [-j oe|eo] [-J X-Y[:Z]]
        [-k o|e|oe] [-l resource_list] [-m mail_options] [-M user_list]
        [-N jobname] [-o path] [-p priority] [-P project] [-q queue] [-r y|n]
        [-S path] [-u user_list] [-W otherattributes=value...]
        [-v variable_list] [-V ] [-z] [script | -- command [arg1 ...]]
       qsub --version
batch queue not available (could not run qsub)
0-element Array{Int64,1}

**Comment by vchuravy** [comment]
Hello John,

If you could provide a PR that detects PBSPro and then not uses `-t` that would be great!

**Comment by hearnsj** [comment]
Valentin, I will look at that.
I think that the Batch System world has changed.   PBSPro is different from OpenPBS.
PBSPro is now a dual model - Open Source with support from Altair if you choose to purchase it.
I think PBSPro will therefore become much more used than OpenPBS.
I think we need another provider:

addprocs_pbspro( np::Integer, queue="") or addprocs(PBSproManager(np,queue))

**Comment by snirgaz** [comment]
Any update of PBSPro support?
It seems like changing "-t" to "-J" should od the trick.

**Comment by darrencl** [comment]
Any update on this?

**Comment by juliohm** [comment]
Please feel free to submit a PR against the latest master branch.
