### ISSUE TITLE
Recommend using `salloc` before using SlurmManager

### ISSUE THREAD

**Issue by brenhinkeller** [JuliaParallel/ClusterManagers.jl#92]
Using addprocs_slurm to add 160 workers on a cluster, I noticed that workers were being dropped every 220 seconds while waiting for resources to be allocated. Commenting out lines 51:54 in  https://github.com/JuliaParallel/ClusterManagers.jl/blob/master/src/slurm.jl 
```julia
if time() > t0 + 60 + np
    warn("dropping worker: file not created in $(60 + np) seconds")
    break
end
````
fixed the problem, but this is a hack. Presumably there should be a way to start this timeout countdown only after resources have been allocated / the job has made it through the slurm batch queue.

**Comment by brenhinkeller** [comment]
Is this project dead?

**Comment by vchuravy** [comment]
No, just very resource constrained.

I would recommend to first `salloc` the resources you need and then use the ClusterManager to start the jobs.

**Comment by brenhinkeller** [comment]
Thank you! You can close this then unless this is something you want to change in the future anyways
